import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import ReactQueryProvider from "./_components/context/ReactQueryProvider";
import Header from "./_components/mainComponents/Header";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Somana : Explore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        <ChakraProvider>
          <ReactQueryProvider>
            <div>
              <div className="fixed top-0 w-full z-10">
                <Header />
              </div>
              <div className="h-12"></div>
              {children}
            </div>
          </ReactQueryProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
