import { DM_Sans } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import ReactQueryProvider from "./_components/context/ReactQueryProvider";
import Header from "./_components/mainComponents/Header";
import { ReactThemeProvider } from "./_components/context/ReactThemeProvider";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Somana : Explore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} antialiased dark:bg-black dark:text-stone-50`}
      >
        <ReactThemeProvider>
          <ChakraProvider>
            <ReactQueryProvider>
              <div>
                <div className="fixed top-0 w-full z-10">
                  <Header />
                </div>
                <div className="h-12"></div>
                {children}
              </div>
            </ReactQueryProvider>
          </ChakraProvider>
        </ReactThemeProvider>
      </body>
    </html>
  );
}
